ass_parameters:
  fontname: 'Impact'
  fontsize: 0.08
  PrimaryColour: '&H0001B5E0'
  SecondaryColour: '&H0000FF00'
  OutlineColour: '&H00000000'
  BackColour: '&H64000000'
  BorderStyle: 1 
  Outline: 7
  Alignment: 5
  Shadow: 10
  MarginL: 50
  MarginR: 50 
  MarginV: 0.20

special_effects:
  zoom_in: True
  box_highlight: False
  color_highlight: False
  karaoke_highlight: False

subtitles_parameters:
  max_words: 3
  max_length: 20
  upper_case: True